server:
  port: 8090
spring:
  application:
    name: service-provider
  cloud:
    consul:
      host: 192.168.141.238
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true

logging:
  level:
    org.springframework.cloud.consul: DEBUG
