server:
  port: 8091
spring:
  application:
    name: service-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true

logging:
  level:
    org.springframework.cloud.consul: DEBUG